# Generated by Django 5.1.15 on 2026-06-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1024)),
                ('scope', models.CharField(choices=[('local', 'Local'), ('web', 'Web')], default='local', max_length=8)),
                ('depth', models.CharField(choices=[('quick', 'Quick'), ('standard', 'Standard'), ('deep', 'Deep')], default='standard', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
