# Generated by Django 5.1.15 on 2026-06-25 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('base_branch', models.CharField(default='app/developer', max_length=200)),
                ('race_mode', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('merged', 'Merged')], default='running', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FleetLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('worktree_path', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('status_label', models.CharField(default='queued', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('elapsed', models.CharField(blank=True, max_length=16)),
                ('route', models.CharField(choices=[('local', 'Local'), ('cloud', 'Cloud'), ('denied', 'Denied')], default='local', max_length=8)),
                ('cost', models.CharField(blank=True, max_length=16)),
                ('is_winner', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanes', to='fleet.fleetrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FleetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.CharField(max_length=16)),
                ('actor', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=255)),
                ('outcome', models.CharField(blank=True, max_length=128)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fleet.fleetrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
