pragma Singleton

import QtQuick 2.15
import "ThemeData.js" as ThemeData

Item{
    id: colorId

    property string currentTheme: "editra"
    property string theme: isDarkTheme ? "Dark" : "Light"

    property var _p: ThemeData.getPalette(currentTheme, theme)
    onCurrentThemeChanged: _p = ThemeData.getPalette(currentTheme, theme)
    onThemeChanged: _p = ThemeData.getPalette(currentTheme, theme)

    property var currentTextColor:          _p.textColor
    property var currentTextSelectionColor: _p.textSelectionColor
    property var currentBackgroundColor:    _p.backgroundColor
    property var currentPrimaryColor:       _p.primaryColor
    property var currentErrorColor:         _p.errorColor
    property var currentSuccessColor:       _p.successColor
    property var currentwarningColor:       _p.warningColor
    property var currentInfoColor:          _p.infoColor
    property var currentOrangeColor:        _p.orangeColor
    property var currentMagentaColor:       _p.magentaColor
    property var currentOverlayColor:       _p.overlayColor
    property var currentAvatarBGDynamicColor:
        ["#82B536","#F15B50","#F38A3F","#CF9F02","#2ABB7F","#42B2D7","#388BFF","#8F7EE7","#DA62AC", currentBackgroundColor[3]]
    property var currentColorForBlueLayers: (theme === "Light")
        ? ["#091E4208","#091E420F","#091E424F","#091E424F","#091E427D"]
        : ["#BCD6F00A","#A1BDD914","#A6C5E229","#BFDBF847","#9BB4CA80"]

    readonly property color menuNormalIcon: currentBackgroundColor[4]
    readonly property color menuHoverAndCheckedIcon: currentPrimaryColor[2]
    readonly property color menuHoverBackground: currentBackgroundColor[2]
    readonly property color menuShowCheckedRectangle: currentPrimaryColor[2]
    readonly property color menuBackground: currentBackgroundColor[2]
    readonly property color transparent: "#00ffffff"
    readonly property color background: currentBackgroundColor[0]
    readonly property color menu: currentBackgroundColor[1]
    readonly property color overlay: currentOverlayColor[1]
    readonly property color overlayDrawer: currentOverlayColor[0]
    readonly property color toolTipText: currentTextColor[6]
    readonly property color toolTipBackground: currentBackgroundColor[0]
    readonly property color toolTipGlowAndBorder: currentBackgroundColor[3]
    readonly property color textTitle: currentTextColor[6]
    readonly property color textInformation: currentTextColor[5]
    readonly property color textTagInfo: currentSuccessColor[2]
    readonly property color textTagDebug: currentInfoColor[2]
    readonly property color textTagError: currentErrorColor[2]
    readonly property color textTagWarning: currentAvatarBGDynamicColor[8]
    readonly property color textTagCritical: currentErrorColor[2]
    readonly property color textTagFatal: currentErrorColor[2]
    readonly property color textSelection: currentTextSelectionColor[1]
    readonly property color textPlaceholder: currentTextSelectionColor[0]
    readonly property color iconPrimaryNormal: currentBackgroundColor[4]
    readonly property color iconPrimaryHoverAndChecked: currentPrimaryColor[2]
    readonly property color iconFeatureBlueNormal: currentInfoColor[1]
    readonly property color iconFeatureBlueHoverAndChecked: currentInfoColor[2]
    readonly property color iconFeatureBlueBackground: currentInfoColor[0]
    readonly property color iconFeatureRedNormal: currentErrorColor[1]
    readonly property color iconFeatureRedHoverAndChecked: currentErrorColor[2]
    readonly property color iconFeatureRedBackground: currentErrorColor[0]
    readonly property color iconFeatureOrangeNormal: currentOrangeColor[1]
    readonly property color iconFeatureOrangeHoverAndChecked: currentOrangeColor[2]
    readonly property color iconFeatureOrangeBackground: currentOrangeColor[0]
    readonly property color iconFeatureMagentaNormal: currentMagentaColor[1]
    readonly property color iconFeatureMagentaHoverAndChecked: currentMagentaColor[2]
    readonly property color iconFeatureMagentaBackground: currentMagentaColor[0]
    readonly property color iconFeatureYellowNormal: currentwarningColor[1]
    readonly property color iconFeatureYellowHoverAndChecked: currentwarningColor[2]
    readonly property color iconFeatureYellowBackground: currentwarningColor[0]
    readonly property color iconFeatureGreenNormal: currentSuccessColor[1]
    readonly property color iconFeatureGreenHoverAndChecked: currentSuccessColor[2]
    readonly property color iconFeatureGreenBackground: currentSuccessColor[0]
    readonly property color buttonPrimaryNormal: currentPrimaryColor[2]
    readonly property color buttonPrimaryHover: currentPrimaryColor[3]
    readonly property color buttonPrimaryPressed: currentPrimaryColor[4]
    readonly property color buttonPrimaryDisabled: currentPrimaryColor[1]
    readonly property color buttonPrimarySelected: currentBackgroundColor[2]
    readonly property color buttonPrimaryBorderNormal: currentPrimaryColor[2]
    readonly property color buttonPrimaryBorderHover: currentPrimaryColor[3]
    readonly property color buttonPrimaryBorderPressed: currentPrimaryColor[4]
    readonly property color buttonPrimaryBorderDisabled: currentPrimaryColor[1]
    readonly property color buttonPrimaryBorderSelected: currentPrimaryColor[0]
    readonly property color buttonPrimaryTextNormal: currentTextColor[0]
    readonly property color buttonPrimaryTextHover: currentTextColor[0]
    readonly property color buttonPrimaryTextPressed: currentTextColor[0]
    readonly property color buttonPrimaryTextDisabled: currentTextColor[3]
    readonly property color buttonPrimaryTextSelected: currentTextColor[1]
    readonly property color buttonSecondaryNormal: currentPrimaryColor[0]
    readonly property color buttonSecondaryHover: currentBackgroundColor[3]
    readonly property color buttonSecondaryPressed: currentPrimaryColor[1]
    readonly property color buttonSecondaryDisabled: currentPrimaryColor[1]
    readonly property color buttonSecondarySelected: currentBackgroundColor[2]
    readonly property color buttonSecondaryBorderNormal: currentPrimaryColor[0]
    readonly property color buttonSecondaryBorderHover: currentPrimaryColor[2]
    readonly property color buttonSecondaryBorderPressed: currentPrimaryColor[3]
    readonly property color buttonSecondaryBorderDisabled: currentPrimaryColor[1]
    readonly property color buttonSecondaryBorderSelected: currentPrimaryColor[2]
    readonly property color buttonSecondaryTextNormal: currentTextColor[3]
    readonly property color buttonSecondaryTextHover: currentTextColor[4]
    readonly property color buttonSecondaryTextPressed: currentTextColor[5]
    readonly property color buttonSecondaryTextDisabled: currentTextColor[6]
    readonly property color buttonSecondaryTextSelected: currentPrimaryColor[2]
    readonly property color buttonDangerNormal: currentErrorColor[2]
    readonly property color buttonDangerHover: currentErrorColor[3]
    readonly property color buttonDangerPressed: currentErrorColor[4]
    readonly property color buttonDangerDisabled: currentErrorColor[1]
    readonly property color buttonDangerSelected: currentErrorColor[0]
    readonly property color buttonDangerBorderNormal: currentErrorColor[2]
    readonly property color buttonDangerBorderHover: currentErrorColor[3]
    readonly property color buttonDangerBorderPressed: currentErrorColor[4]
    readonly property color buttonDangerBorderDisabled: currentErrorColor[1]
    readonly property color buttonDangerBorderSelected: currentErrorColor[0]
    readonly property color buttonDangerTextNormal: currentTextColor[0]
    readonly property color buttonDangerTextHover: currentTextColor[0]
    readonly property color buttonDangerTextPressed: currentTextColor[0]
    readonly property color buttonDangerTextDisabled: currentTextColor[3]
    readonly property color buttonDangerTextSelected: currentTextColor[1]
    readonly property color buttonFeatureNormal: transparent
    readonly property color buttonFeatureHover: currentBackgroundColor[2]
    readonly property color buttonFeaturePressed: currentPrimaryColor[1]
    readonly property color buttonFeatureDisabled: currentPrimaryColor[1]
    readonly property color buttonFeatureSelected: currentBackgroundColor[2]
    readonly property color buttonFeatureBorderNormal: currentBackgroundColor[2]
    readonly property color buttonFeatureBorderHover: currentBackgroundColor[3]
    readonly property color buttonFeatureBorderPressed: currentPrimaryColor[2]
    readonly property color buttonFeatureBorderDisabled: currentPrimaryColor[0]
    readonly property color buttonFeatureBorderSelected: currentPrimaryColor[1]
    readonly property color buttonFeatureTextNormal: currentTextColor[3]
    readonly property color buttonFeatureTextHover: currentTextColor[4]
    readonly property color buttonFeatureTextPressed: currentTextColor[5]
    readonly property color buttonFeatureTextDisabled: currentTextColor[6]
    readonly property color buttonFeatureTextSelected: currentPrimaryColor[2]
    readonly property color buttonProgressNormal: currentPrimaryColor[1]
    readonly property color buttonProgressHover: currentPrimaryColor[2]
    readonly property color buttonProgressPressed: currentPrimaryColor[2]
    readonly property color buttonProgressDisabled: currentPrimaryColor[1]
    readonly property color buttonProgressSelected: currentPrimaryColor[1]
    readonly property color buttonProgressNormalGradient0: currentPrimaryColor[2]
    readonly property color buttonProgressHoverGradient0: currentPrimaryColor[3]
    readonly property color buttonProgressPressedGradient0: currentPrimaryColor[3]
    readonly property color buttonProgressDisabledGradient0: currentPrimaryColor[0]
    readonly property color buttonProgressSelectedGradient0: currentPrimaryColor[0]
    readonly property color buttonProgressNormalGradient1: currentPrimaryColor[3]
    readonly property color buttonProgressHoverGradient1: currentPrimaryColor[4]
    readonly property color buttonProgressPressedGradient1: currentPrimaryColor[4]
    readonly property color buttonProgressDisabledGradient1: currentPrimaryColor[3]
    readonly property color buttonProgressSelectedGradient1: currentPrimaryColor[3]
    readonly property color buttonProgressBorderNormal: currentPrimaryColor[1]
    readonly property color buttonProgressBorderHover: currentPrimaryColor[2]
    readonly property color buttonProgressBorderPressed: currentPrimaryColor[3]
    readonly property color buttonProgressBorderDisabled: currentPrimaryColor[0]
    readonly property color buttonProgressBorderSelected: currentPrimaryColor[0]
    readonly property color buttonProgressTextNormal: currentTextColor[0]
    readonly property color buttonProgressTextHover: currentTextColor[0]
    readonly property color buttonProgressTextPressed: currentTextColor[0]
    readonly property color buttonProgressTextDisabled: currentTextColor[3]
    readonly property color buttonProgressTextSelected: currentTextColor[1]
    readonly property color boxNormalGradient0: currentBackgroundColor[1]
    readonly property color boxNormalGradient1: currentBackgroundColor[3]
    readonly property color boxHoverGradient0: currentBackgroundColor[1]
    readonly property color boxHoverGradient1: currentBackgroundColor[3]
    readonly property color boxBorder: currentBackgroundColor[3]
    readonly property color boxChecked: currentPrimaryColor[0]
    readonly property color boxHover: currentBackgroundColor[1]
    readonly property color boxSuccessColor: currentSuccessColor[0]
    readonly property color like: currentErrorColor[1]
    readonly property color progressBarText: currentTextColor[6]
    readonly property color progressBarBackground: currentPrimaryColor[0]
    readonly property color progressBarGradient0: currentPrimaryColor[1]
    readonly property color progressBarGradient1: currentPrimaryColor[3]
    readonly property var availableThemes: [
        "editra", "copper", "obsidian", "indigo", "news", "pencilly", "indox"
    ]
}
