# Generated by Django 5.1.15 on 2026-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('markdown', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
