#!/usr/bin/env python3
"""Phoenix CLI — start the local gateway or configure external clients.

  phoenix                 Start gateway (default)
  phoenix serve           Same as above
  phoenix configure       Write ~/.phoenix/env.sh + optional shell hook
  phoenix configure --claude|--openai|--continue|--all
  phoenix configure --show
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

DEFAULT_PORT = 24678
PHOENIX_DIR = Path.home() / ".phoenix"
ENV_FILE = PHOENIX_DIR / "env.sh"
ENV_FISH = PHOENIX_DIR / "env.fish"
CONTINUE_SNIPPET = PHOENIX_DIR / "continue.phoenix.json"


def install_root() -> Path:
    """Release layout: …/versions/<ver>/cli/ ; dev: repo install/ parent."""
    here = Path(__file__).resolve().parent
    if (here / "bin" / "phoenix-server").exists() or (here.parent / "bin" / "phoenix-server").exists():
        return here.parent if here.name == "bin" else here
    # Running from source: install/phoenix_cli.py
    return here.parent / "packages" / "phoenix_server"


def gateway_base(port: int) -> str:
    return f"http://127.0.0.1:{port}"


def env_lines(port: int, *, claude: bool, openai: bool) -> list[str]:
    base = gateway_base(port)
    lines = [
        "# Phoenix local gateway — generated by: phoenix configure",
        f"export PHOENIX_GATEWAY_PORT={port}",
        f"export PHOENIX_GATEWAY_URL={base}",
    ]
    if claude:
        lines += [
            f"export ANTHROPIC_BASE_URL={base}",
            "export ANTHROPIC_API_KEY=phoenix-local",
        ]
    if openai:
        lines += [
            f"export OPENAI_BASE_URL={base}/v1",
            f"export OPENAI_API_BASE={base}/v1",
            "export OPENAI_API_KEY=phoenix-local",
        ]
    return lines


def continue_config(port: int) -> dict:
    base = f"{gateway_base(port)}/v1"
    return {
        "models": [
            {
                "title": "Phoenix Local",
                "provider": "openai",
                "model": "local",
                "apiBase": base,
                "apiKey": "phoenix-local",
            }
        ],
        "tabAutocompleteModel": {
            "title": "Phoenix Local",
            "provider": "openai",
            "model": "local",
            "apiBase": base,
            "apiKey": "phoenix-local",
        },
    }


def write_env_fish(port: int, *, claude: bool, openai: bool) -> Path:
    PHOENIX_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Phoenix local gateway — generated by: phoenix configure",
        f"set -gx PHOENIX_GATEWAY_PORT {port}",
        f"set -gx PHOENIX_GATEWAY_URL {gateway_base(port)}",
    ]
    if claude:
        lines += [
            f"set -gx ANTHROPIC_BASE_URL {gateway_base(port)}",
            "set -gx ANTHROPIC_API_KEY phoenix-local",
        ]
    if openai:
        lines += [
            f"set -gx OPENAI_BASE_URL {gateway_base(port)}/v1",
            f"set -gx OPENAI_API_BASE {gateway_base(port)}/v1",
            "set -gx OPENAI_API_KEY phoenix-local",
        ]
    ENV_FISH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return ENV_FISH


def write_env_file(port: int, *, claude: bool, openai: bool) -> Path:
    PHOENIX_DIR.mkdir(parents=True, exist_ok=True)
    content = "\n".join(env_lines(port, claude=claude, openai=openai)) + "\n"
    ENV_FILE.write_text(content, encoding="utf-8")
    return ENV_FILE


def write_continue_snippet(port: int) -> Path:
    PHOENIX_DIR.mkdir(parents=True, exist_ok=True)
    CONTINUE_SNIPPET.write_text(json.dumps(continue_config(port), indent=2) + "\n", encoding="utf-8")
    return CONTINUE_SNIPPET


def shell_hook_block() -> str:
    return '\n# Phoenix local gateway\n[ -f "$HOME/.phoenix/env.sh" ] && . "$HOME/.phoenix/env.sh"\n'


def maybe_install_shell_hook(*, dry_run: bool) -> str | None:
    shell = Path(os.environ.get("SHELL", "/bin/bash")).name
    if shell == "fish":
        target = Path.home() / ".config" / "fish" / "config.fish"
        marker = ".phoenix/env.fish"
        hook = '\n# Phoenix local gateway\nsource "$HOME/.phoenix/env.fish"\n'
    elif shell == "zsh":
        target = Path.home() / ".zshrc"
        marker = ".phoenix/env.sh"
        hook = shell_hook_block()
    elif shell == "bash":
        target = Path.home() / ".bashrc"
        if not target.exists():
            target = Path.home() / ".bash_profile"
        marker = ".phoenix/env.sh"
        hook = shell_hook_block()
    else:
        return None

    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    if marker in existing:
        return str(target)

    if dry_run:
        print(f"  would append hook to {target}")
        return str(target)

    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as fh:
        fh.write(hook)
    return str(target)


def cmd_configure(args: argparse.Namespace) -> int:
    port = args.port
    claude = args.claude or args.all
    openai = args.openai or args.all
    cont = args.continue_ or args.all

    if not (claude or openai or cont):
        claude = openai = cont = True

    if args.show:
        print("\n".join(env_lines(port, claude=claude, openai=openai)))
        if cont:
            print("\n# Continue snippet →", CONTINUE_SNIPPET)
            print(json.dumps(continue_config(port), indent=2))
        return 0

    if args.dry_run:
        print(f"▸ Would write {ENV_FILE}")
        print(f"▸ Gateway {gateway_base(port)}")
        if cont:
            print(f"▸ Would write {CONTINUE_SNIPPET}")
        maybe_install_shell_hook(dry_run=True)
        return 0

    path = write_env_file(port, claude=claude, openai=openai)
    print(f"✓ Wrote {path}")
    fish_path = write_env_fish(port, claude=claude, openai=openai)
    print(f"✓ Wrote {fish_path}")

    if cont:
        cpath = write_continue_snippet(port)
        print(f"✓ Wrote {cpath}")
        print("  Merge into ~/.continue/config.json (models + tabAutocompleteModel)")

    hooked = maybe_install_shell_hook(dry_run=False)
    if hooked:
        print(f"✓ Shell hook added to {hooked}")
    else:
        print("  Add to your shell profile:")
        print('    [ -f "$HOME/.phoenix/env.sh" ] && . "$HOME/.phoenix/env.sh"')

    print("\n✨ Configure complete. Start Phoenix, load a model, then:")
    if claude:
        print("  claude          # Claude CLI → local GGUF")
    if openai:
        print("  # OpenAI-compatible tools →", f"{gateway_base(port)}/v1")
    return 0


def cmd_serve(_: argparse.Namespace) -> int:
    root = Path(__file__).resolve().parent
    # Release bundle: phoenix_cli lives in bin/ next to phoenix-server
    if root.name == "bin":
        cli_root = root.parent
    else:
        # Source: install/phoenix_cli.py — run dart server directly
        server_dir = Path(__file__).resolve().parents[1] / "packages" / "phoenix_server"
        if server_dir.is_dir():
            env = os.environ.copy()
            env.setdefault("PHOENIX_DB_PATH", str(PHOENIX_DIR / "data" / "phoenix.db"))
            repo = Path(__file__).resolve().parents[1]
            engine = repo / "engine" / "local_provider" / "linux_llama" / "applocal_provider"
            if engine.exists():
                env["PHOENIX_ENGINE_PATH"] = str(engine)
            return subprocess.run(["dart", "run", "bin/server.dart"], cwd=server_dir, env=env).returncode
        cli_root = root.parent

    server = cli_root / "bin" / "phoenix-server"
    engine = cli_root / "engine" / "applocal_provider"
    env = os.environ.copy()
    if engine.exists():
        env["PHOENIX_ENGINE_PATH"] = str(engine)
    env.setdefault("PHOENIX_DB_PATH", str(PHOENIX_DIR / "data" / "phoenix.db"))
    if not server.exists():
        print(f"✗ phoenix-server not found at {server}", file=sys.stderr)
        return 1
    return subprocess.run([str(server)], env=env).returncode


def main() -> int:
    parser = argparse.ArgumentParser(prog="phoenix", description="Phoenix local LLM gateway")
    parser.add_argument("--port", type=int, default=int(os.environ.get("PHOENIX_GATEWAY_PORT", DEFAULT_PORT)))
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("serve", help="Start the gateway (default)")

    cfg = sub.add_parser("configure", help="Configure Claude CLI and OpenAI-compatible clients")
    cfg.add_argument("--claude", action="store_true", help="Anthropic env (Claude CLI)")
    cfg.add_argument("--openai", action="store_true", help="OpenAI env (Continue, etc.)")
    cfg.add_argument("--continue", dest="continue_", action="store_true", help="Write Continue.dev snippet")
    cfg.add_argument("--all", action="store_true", help="Configure everything (default)")
    cfg.add_argument("--show", action="store_true", help="Print config without writing files")
    cfg.add_argument("--dry-run", action="store_true", help="Show what would be written")

    args = parser.parse_args()
    if args.command == "configure":
        return cmd_configure(args)
    return cmd_serve(args)


if __name__ == "__main__":
    sys.exit(main())
