# Generated by Django 5.1.15 on 2026-06-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('document', 'Document'), ('speech', 'Speech'), ('search', 'Search'), ('developer', 'Developer'), ('evaluator', 'Evaluator'), ('flows', 'Flows')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('installs_count', models.IntegerField(default=0)),
                ('installed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
