# Generated by Django 5.1.15 on 2026-08-03 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_seed_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='installed',
        ),
        migrations.CreateModel(
            name='ExtensionInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='extensions.extension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_installs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('extension', 'user'), name='uniq_install_per_user')],
            },
        ),
    ]
