name: Create Jira Ticket

on:
  issues:
    types: [opened]

jobs:
  create_jira:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira issue
        uses: atlassian/gajira-create@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          project: BUGS  # Replace with your actual Jira project key
          issuetype: Bug
          summary: "${{ github.event.issue.title }}"
          description: |
            ${{ github.event.issue.body }}

            [GitHub Issue Link](${{ github.event.issue.html_url }})
